### ISSUE TITLE
无法被windows及linux运行

### ISSUE THREAD

**Issue by bupt2017** [GuoFlight/yuque_export#1]
windows：不是exe文件，不能双击执行，也不能通过终端运行
linux：不是可执行文件 ./yueque_export也无法执行

请问大佬你这个是怎么运行的啊

**Comment by GuoFlight** [comment]
不好意思，这是在m1芯片的mac上运行的。我有时间更新一下win和linux版本。如果着急的话，你可以手动编译执行。

**Comment by GuoFlight** [comment]
你好，主流系统和芯片架构的可执行程序已经更新到Release中，请查看。如果没有您想要的版本，可以克隆项目，通过go build -o yuque_export来编译得到可执行程序。
