### ISSUE TITLE
在Windows上怎么运行和这个可执行程序

### ISSUE THREAD

**Issue by jhchhz** [GuoFlight/yuque_export#4]
go run yuque_export_win_amd64
package yuque_export_win_amd64 is not in std (C:\Go\src\yuque_export_win_amd64)

**Comment by GuoFlight** [comment]
windows可以按以下步骤使用：
1. 在此页面下载适合自己系统的二进制程序：https://github.com/GuoFlight/yuque_export/releases
2. 在此页面下载配置文件config.toml：https://github.com/GuoFlight/yuque_export
3. 在配置文件中更新cookie和x_csrf_token配置。（这两个配置可以通过语雀页面按下F12拿到）
4. 执行程序。方法1：双击二进制程序(二进制程序和配置文件需要在同一目录下)。方法2：在cmd终端中，输入以下命令，即可将所有笔记下载到output目录下：yuque_export_win_amd64.exe -c config.toml

**Comment by jhchhz** [comment]
> windows可以按以下步骤使用：
> 
> 1. 在此页面下载适合自己系统的二进制程序：https://github.com/GuoFlight/yuque_export/releases
> 2. 在此页面下载配置文件config.toml：https://github.com/GuoFlight/yuque_export
> 3. 在配置文件中更新cookie和x_csrf_token配置。（这两个配置可以通过语雀页面按下F12拿到）
> 4. 执行程序。方法1：双击二进制程序(二进制程序和配置文件需要在同一目录下)。方法2：在cmd终端中，输入以下命令，即可将所有笔记下载到output目录下：yuque_export_win_amd64.exe -c config.toml

非常感谢热心博主还打了exe ，发现用go run main.go 也可以执行，

**Comment by jhchhz** [comment]
就是不能存公共空间的内容，（无法把公共空间复制到自己的空间的情况下），博主，这个有解决思路吗

**Comment by GuoFlight** [comment]
> 就是不能存公共空间的内容，（无法把公共空间复制到自己的空间的情况下），博主，这个有解决思路吗

你说的是别人公开的空间或文档吗？这个本仓库并没有支持。
原因是语雀并没有开放导出"公开文档"这个功能。这也能理解，毕竟那是别人的文档。
所以只能考虑使用其他方式，比如截图、复制粘贴等，但这样就不是markdown格式了。

**Comment by jhchhz** [comment]
> > 就是不能存公共空间的内容，（无法把公共空间复制到自己的空间的情况下），博主，这个有解决思路吗
> 
> 你说的是别人公开的空间或文档吗？这个本仓库并没有支持。 原因是语雀并没有开放导出"公开文档"这个功能。这也能理解，毕竟那是别人的文档。 所以只能考虑使用其他方式，比如截图、复制粘贴等，但这样就不是markdown格式了。

对，公共空间，但不是管理员，无法转存到个人空间，找到的别的方法需要token，不知道是否可以，

**Comment by GuoFlight** [comment]
只要官方能够导出，就可以实现。如果有这种功能，你可以给一个样例。
