### ISSUE TITLE
不行哦，运行出来只有一个空的文件夹

### ISSUE THREAD

**Issue by lhshuasheng** [GuoFlight/yuque_export#5]
![Uploading Snipaste_2024-02-25_20-38-33.png…]()

**Comment by GuoFlight** [comment]
这个图片看起来无法访问了，再上传一遍看看？包括你的配置，使用方法，电脑系统等信息

**Comment by lhshuasheng** [comment]
没事了哈哈，公共文档无法下载的，我的问题
